package com.qiu.Mapper;

import com.qiu.pojo.audioTable;
import com.qiu.pojo.audioTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface audioTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AudioTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int countByExample(audioTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AudioTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int deleteByExample(audioTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AudioTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int deleteByPrimaryKey(Integer audioId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AudioTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int insert(audioTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AudioTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int insertSelective(audioTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AudioTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    List<audioTable> selectByExampleWithBLOBs(audioTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AudioTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    List<audioTable> selectByExample(audioTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AudioTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    audioTable selectByPrimaryKey(Integer audioId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AudioTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int updateByExampleSelective(@Param("record") audioTable record, @Param("example") audioTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AudioTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") audioTable record, @Param("example") audioTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AudioTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int updateByExample(@Param("record") audioTable record, @Param("example") audioTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AudioTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int updateByPrimaryKeySelective(audioTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AudioTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(audioTable record);
}