package com.qiu.Mapper;

import com.qiu.pojo.carrier_code_info;
import com.qiu.pojo.carrier_code_infoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface carrier_code_infoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int countByExample(carrier_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int deleteByExample(carrier_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int deleteByPrimaryKey(String carrierCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int insert(carrier_code_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int insertSelective(carrier_code_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    List<carrier_code_info> selectByExample(carrier_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    carrier_code_info selectByPrimaryKey(String carrierCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int updateByExampleSelective(@Param("record") carrier_code_info record, @Param("example") carrier_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int updateByExample(@Param("record") carrier_code_info record, @Param("example") carrier_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int updateByPrimaryKeySelective(carrier_code_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int updateByPrimaryKey(carrier_code_info record);
}