package com.qiu.Mapper;

import com.qiu.pojo.disaster_code_info;
import com.qiu.pojo.disaster_code_infoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface disaster_code_infoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disaster_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int countByExample(disaster_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disaster_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int deleteByExample(disaster_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disaster_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int deleteByPrimaryKey(String disasterCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disaster_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int insert(disaster_code_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disaster_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int insertSelective(disaster_code_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disaster_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    List<disaster_code_info> selectByExample(disaster_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disaster_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    disaster_code_info selectByPrimaryKey(String disasterCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disaster_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int updateByExampleSelective(@Param("record") disaster_code_info record, @Param("example") disaster_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disaster_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int updateByExample(@Param("record") disaster_code_info record, @Param("example") disaster_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disaster_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int updateByPrimaryKeySelective(disaster_code_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disaster_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int updateByPrimaryKey(disaster_code_info record);
}