package com.qiu.Mapper;

import com.qiu.pojo.geo_code_info;
import com.qiu.pojo.geo_code_infoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface geo_code_infoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int countByExample(geo_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int deleteByExample(geo_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int deleteByPrimaryKey(String geoCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int insert(geo_code_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int insertSelective(geo_code_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    List<geo_code_info> selectByExample(geo_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    geo_code_info selectByPrimaryKey(String geoCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int updateByExampleSelective(@Param("record") geo_code_info record, @Param("example") geo_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int updateByExample(@Param("record") geo_code_info record, @Param("example") geo_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int updateByPrimaryKeySelective(geo_code_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int updateByPrimaryKey(geo_code_info record);
}