package com.qiu.Mapper;

import com.qiu.pojo.imageTable;
import com.qiu.pojo.imageTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface imageTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImageTable
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    int countByExample(imageTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImageTable
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    int deleteByExample(imageTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImageTable
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    int deleteByPrimaryKey(Integer imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImageTable
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    int insert(imageTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImageTable
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    int insertSelective(imageTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImageTable
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    List<imageTable> selectByExampleWithBLOBs(imageTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImageTable
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    List<imageTable> selectByExample(imageTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImageTable
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    imageTable selectByPrimaryKey(Integer imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImageTable
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    int updateByExampleSelective(@Param("record") imageTable record, @Param("example") imageTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImageTable
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") imageTable record, @Param("example") imageTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImageTable
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    int updateByExample(@Param("record") imageTable record, @Param("example") imageTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImageTable
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    int updateByPrimaryKeySelective(imageTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImageTable
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(imageTable record);
}