package com.qiu.Mapper;

import com.qiu.pojo.source_code_info;
import com.qiu.pojo.source_code_infoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface source_code_infoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int countByExample(source_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int deleteByExample(source_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int deleteByPrimaryKey(String sourceCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int insert(source_code_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int insertSelective(source_code_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    List<source_code_info> selectByExample(source_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    source_code_info selectByPrimaryKey(String sourceCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int updateByExampleSelective(@Param("record") source_code_info record, @Param("example") source_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int updateByExample(@Param("record") source_code_info record, @Param("example") source_code_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int updateByPrimaryKeySelective(source_code_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    int updateByPrimaryKey(source_code_info record);
}