package com.qiu.Mapper;

import com.qiu.pojo.videoTable;
import com.qiu.pojo.videoTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface videoTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VideoTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int countByExample(videoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VideoTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int deleteByExample(videoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VideoTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int deleteByPrimaryKey(Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VideoTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int insert(videoTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VideoTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int insertSelective(videoTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VideoTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    List<videoTable> selectByExampleWithBLOBs(videoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VideoTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    List<videoTable> selectByExample(videoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VideoTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    videoTable selectByPrimaryKey(Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VideoTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int updateByExampleSelective(@Param("record") videoTable record, @Param("example") videoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VideoTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") videoTable record, @Param("example") videoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VideoTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int updateByExample(@Param("record") videoTable record, @Param("example") videoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VideoTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int updateByPrimaryKeySelective(videoTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VideoTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(videoTable record);
}