package com.qiu.pojo;

public class carrier_code_info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carrier_code_info.carrier_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String carrierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carrier_code_info.carrier_form
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String carrierForm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carrier_code_info.carrier_code
     *
     * @return the value of carrier_code_info.carrier_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getCarrierCode() {
        return carrierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carrier_code_info.carrier_code
     *
     * @param carrierCode the value for carrier_code_info.carrier_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setCarrierCode(String carrierCode) {
        this.carrierCode = carrierCode == null ? null : carrierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carrier_code_info.carrier_form
     *
     * @return the value of carrier_code_info.carrier_form
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getCarrierForm() {
        return carrierForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carrier_code_info.carrier_form
     *
     * @param carrierForm the value for carrier_code_info.carrier_form
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setCarrierForm(String carrierForm) {
        this.carrierForm = carrierForm == null ? null : carrierForm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", carrierCode=").append(carrierCode);
        sb.append(", carrierForm=").append(carrierForm);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        carrier_code_info other = (carrier_code_info) that;
        return (this.getCarrierCode() == null ? other.getCarrierCode() == null : this.getCarrierCode().equals(other.getCarrierCode()))
            && (this.getCarrierForm() == null ? other.getCarrierForm() == null : this.getCarrierForm().equals(other.getCarrierForm()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCarrierCode() == null) ? 0 : getCarrierCode().hashCode());
        result = prime * result + ((getCarrierForm() == null) ? 0 : getCarrierForm().hashCode());
        return result;
    }
}