package com.qiu.pojo;

public class disaster_code_info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disaster_code_info.disaster_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String disasterCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disaster_code_info.main_category
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String mainCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disaster_code_info.sub_category
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String subCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disaster_code_info.disaster_indicators
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String disasterIndicators;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disaster_code_info.disaster_code
     *
     * @return the value of disaster_code_info.disaster_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getDisasterCode() {
        return disasterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disaster_code_info.disaster_code
     *
     * @param disasterCode the value for disaster_code_info.disaster_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setDisasterCode(String disasterCode) {
        this.disasterCode = disasterCode == null ? null : disasterCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disaster_code_info.main_category
     *
     * @return the value of disaster_code_info.main_category
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getMainCategory() {
        return mainCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disaster_code_info.main_category
     *
     * @param mainCategory the value for disaster_code_info.main_category
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setMainCategory(String mainCategory) {
        this.mainCategory = mainCategory == null ? null : mainCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disaster_code_info.sub_category
     *
     * @return the value of disaster_code_info.sub_category
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getSubCategory() {
        return subCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disaster_code_info.sub_category
     *
     * @param subCategory the value for disaster_code_info.sub_category
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setSubCategory(String subCategory) {
        this.subCategory = subCategory == null ? null : subCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disaster_code_info.disaster_indicators
     *
     * @return the value of disaster_code_info.disaster_indicators
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getDisasterIndicators() {
        return disasterIndicators;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disaster_code_info.disaster_indicators
     *
     * @param disasterIndicators the value for disaster_code_info.disaster_indicators
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setDisasterIndicators(String disasterIndicators) {
        this.disasterIndicators = disasterIndicators == null ? null : disasterIndicators.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disaster_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", disasterCode=").append(disasterCode);
        sb.append(", mainCategory=").append(mainCategory);
        sb.append(", subCategory=").append(subCategory);
        sb.append(", disasterIndicators=").append(disasterIndicators);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disaster_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        disaster_code_info other = (disaster_code_info) that;
        return (this.getDisasterCode() == null ? other.getDisasterCode() == null : this.getDisasterCode().equals(other.getDisasterCode()))
            && (this.getMainCategory() == null ? other.getMainCategory() == null : this.getMainCategory().equals(other.getMainCategory()))
            && (this.getSubCategory() == null ? other.getSubCategory() == null : this.getSubCategory().equals(other.getSubCategory()))
            && (this.getDisasterIndicators() == null ? other.getDisasterIndicators() == null : this.getDisasterIndicators().equals(other.getDisasterIndicators()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disaster_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDisasterCode() == null) ? 0 : getDisasterCode().hashCode());
        result = prime * result + ((getMainCategory() == null) ? 0 : getMainCategory().hashCode());
        result = prime * result + ((getSubCategory() == null) ? 0 : getSubCategory().hashCode());
        result = prime * result + ((getDisasterIndicators() == null) ? 0 : getDisasterIndicators().hashCode());
        return result;
    }
}