package com.qiu.pojo;

public class geo_code_info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geo_code_info.geo_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String geoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geo_code_info.province
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geo_code_info.city
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geo_code_info.county
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geo_code_info.town
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String town;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geo_code_info.village
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String village;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geo_code_info.geo_code
     *
     * @return the value of geo_code_info.geo_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getGeoCode() {
        return geoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geo_code_info.geo_code
     *
     * @param geoCode the value for geo_code_info.geo_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setGeoCode(String geoCode) {
        this.geoCode = geoCode == null ? null : geoCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geo_code_info.province
     *
     * @return the value of geo_code_info.province
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geo_code_info.province
     *
     * @param province the value for geo_code_info.province
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geo_code_info.city
     *
     * @return the value of geo_code_info.city
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geo_code_info.city
     *
     * @param city the value for geo_code_info.city
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geo_code_info.county
     *
     * @return the value of geo_code_info.county
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geo_code_info.county
     *
     * @param county the value for geo_code_info.county
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geo_code_info.town
     *
     * @return the value of geo_code_info.town
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getTown() {
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geo_code_info.town
     *
     * @param town the value for geo_code_info.town
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setTown(String town) {
        this.town = town == null ? null : town.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geo_code_info.village
     *
     * @return the value of geo_code_info.village
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getVillage() {
        return village;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geo_code_info.village
     *
     * @param village the value for geo_code_info.village
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setVillage(String village) {
        this.village = village == null ? null : village.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", geoCode=").append(geoCode);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", county=").append(county);
        sb.append(", town=").append(town);
        sb.append(", village=").append(village);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        geo_code_info other = (geo_code_info) that;
        return (this.getGeoCode() == null ? other.getGeoCode() == null : this.getGeoCode().equals(other.getGeoCode()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getCounty() == null ? other.getCounty() == null : this.getCounty().equals(other.getCounty()))
            && (this.getTown() == null ? other.getTown() == null : this.getTown().equals(other.getTown()))
            && (this.getVillage() == null ? other.getVillage() == null : this.getVillage().equals(other.getVillage()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGeoCode() == null) ? 0 : getGeoCode().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getCounty() == null) ? 0 : getCounty().hashCode());
        result = prime * result + ((getTown() == null) ? 0 : getTown().hashCode());
        result = prime * result + ((getVillage() == null) ? 0 : getVillage().hashCode());
        return result;
    }
}