package com.qiu.pojo;

public class imageTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ImageTable.image_id
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    private Integer imageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ImageTable.image_data
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    private byte[] imageData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ImageTable.image_id
     *
     * @return the value of ImageTable.image_id
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    public Integer getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ImageTable.image_id
     *
     * @param imageId the value for ImageTable.image_id
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ImageTable.image_data
     *
     * @return the value of ImageTable.image_data
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    public byte[] getImageData() {
        return imageData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ImageTable.image_data
     *
     * @param imageData the value for ImageTable.image_data
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    public void setImageData(byte[] imageData) {
        this.imageData = imageData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImageTable
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", imageId=").append(imageId);
        sb.append(", imageData=").append(imageData);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImageTable
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        imageTable other = (imageTable) that;
        return (this.getImageId() == null ? other.getImageId() == null : this.getImageId().equals(other.getImageId()))
            && (this.getImageData() == null ? other.getImageData() == null : this.getImageData().equals(other.getImageData()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImageTable
     *
     * @mbggenerated Mon Nov 06 11:10:43 CST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getImageId() == null) ? 0 : getImageId().hashCode());
        result = prime * result + ((getImageData() == null) ? 0 : getImageData().hashCode());
        return result;
    }
}