package com.qiu.pojo;

public class source_code_info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_code_info.source_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String sourceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_code_info.main_category
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String mainCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_code_info.sub_category
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String subCategory;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_code_info.source_code
     *
     * @return the value of source_code_info.source_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getSourceCode() {
        return sourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_code_info.source_code
     *
     * @param sourceCode the value for source_code_info.source_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode == null ? null : sourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_code_info.main_category
     *
     * @return the value of source_code_info.main_category
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getMainCategory() {
        return mainCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_code_info.main_category
     *
     * @param mainCategory the value for source_code_info.main_category
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setMainCategory(String mainCategory) {
        this.mainCategory = mainCategory == null ? null : mainCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_code_info.sub_category
     *
     * @return the value of source_code_info.sub_category
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getSubCategory() {
        return subCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_code_info.sub_category
     *
     * @param subCategory the value for source_code_info.sub_category
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setSubCategory(String subCategory) {
        this.subCategory = subCategory == null ? null : subCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sourceCode=").append(sourceCode);
        sb.append(", mainCategory=").append(mainCategory);
        sb.append(", subCategory=").append(subCategory);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        source_code_info other = (source_code_info) that;
        return (this.getSourceCode() == null ? other.getSourceCode() == null : this.getSourceCode().equals(other.getSourceCode()))
            && (this.getMainCategory() == null ? other.getMainCategory() == null : this.getMainCategory().equals(other.getMainCategory()))
            && (this.getSubCategory() == null ? other.getSubCategory() == null : this.getSubCategory().equals(other.getSubCategory()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_code_info
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSourceCode() == null) ? 0 : getSourceCode().hashCode());
        result = prime * result + ((getMainCategory() == null) ? 0 : getMainCategory().hashCode());
        result = prime * result + ((getSubCategory() == null) ? 0 : getSubCategory().hashCode());
        return result;
    }
}