package com.qiu.pojo;

public class unified_code {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_code.coding_id
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private Integer codingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_code.geo_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String geoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_code.time_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String timeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_code.source_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String sourceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_code.carrier_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String carrierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_code.disaster_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String disasterCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_code.description
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_code.coding_id
     *
     * @return the value of unified_code.coding_id
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public Integer getCodingId() {
        return codingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_code.coding_id
     *
     * @param codingId the value for unified_code.coding_id
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setCodingId(Integer codingId) {
        this.codingId = codingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_code.geo_code
     *
     * @return the value of unified_code.geo_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getGeoCode() {
        return geoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_code.geo_code
     *
     * @param geoCode the value for unified_code.geo_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setGeoCode(String geoCode) {
        this.geoCode = geoCode == null ? null : geoCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_code.time_code
     *
     * @return the value of unified_code.time_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getTimeCode() {
        return timeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_code.time_code
     *
     * @param timeCode the value for unified_code.time_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setTimeCode(String timeCode) {
        this.timeCode = timeCode == null ? null : timeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_code.source_code
     *
     * @return the value of unified_code.source_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getSourceCode() {
        return sourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_code.source_code
     *
     * @param sourceCode the value for unified_code.source_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode == null ? null : sourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_code.carrier_code
     *
     * @return the value of unified_code.carrier_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getCarrierCode() {
        return carrierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_code.carrier_code
     *
     * @param carrierCode the value for unified_code.carrier_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setCarrierCode(String carrierCode) {
        this.carrierCode = carrierCode == null ? null : carrierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_code.disaster_code
     *
     * @return the value of unified_code.disaster_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getDisasterCode() {
        return disasterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_code.disaster_code
     *
     * @param disasterCode the value for unified_code.disaster_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setDisasterCode(String disasterCode) {
        this.disasterCode = disasterCode == null ? null : disasterCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_code.description
     *
     * @return the value of unified_code.description
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_code.description
     *
     * @param description the value for unified_code.description
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", codingId=").append(codingId);
        sb.append(", geoCode=").append(geoCode);
        sb.append(", timeCode=").append(timeCode);
        sb.append(", sourceCode=").append(sourceCode);
        sb.append(", carrierCode=").append(carrierCode);
        sb.append(", disasterCode=").append(disasterCode);
        sb.append(", description=").append(description);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        unified_code other = (unified_code) that;
        return (this.getCodingId() == null ? other.getCodingId() == null : this.getCodingId().equals(other.getCodingId()))
            && (this.getGeoCode() == null ? other.getGeoCode() == null : this.getGeoCode().equals(other.getGeoCode()))
            && (this.getTimeCode() == null ? other.getTimeCode() == null : this.getTimeCode().equals(other.getTimeCode()))
            && (this.getSourceCode() == null ? other.getSourceCode() == null : this.getSourceCode().equals(other.getSourceCode()))
            && (this.getCarrierCode() == null ? other.getCarrierCode() == null : this.getCarrierCode().equals(other.getCarrierCode()))
            && (this.getDisasterCode() == null ? other.getDisasterCode() == null : this.getDisasterCode().equals(other.getDisasterCode()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCodingId() == null) ? 0 : getCodingId().hashCode());
        result = prime * result + ((getGeoCode() == null) ? 0 : getGeoCode().hashCode());
        result = prime * result + ((getTimeCode() == null) ? 0 : getTimeCode().hashCode());
        result = prime * result + ((getSourceCode() == null) ? 0 : getSourceCode().hashCode());
        result = prime * result + ((getCarrierCode() == null) ? 0 : getCarrierCode().hashCode());
        result = prime * result + ((getDisasterCode() == null) ? 0 : getDisasterCode().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }
}