package com.qiu.pojo;

import java.util.ArrayList;
import java.util.List;

public class unified_codeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unified_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unified_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unified_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public unified_codeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table unified_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCodingIdIsNull() {
            addCriterion("coding_id is null");
            return (Criteria) this;
        }

        public Criteria andCodingIdIsNotNull() {
            addCriterion("coding_id is not null");
            return (Criteria) this;
        }

        public Criteria andCodingIdEqualTo(Integer value) {
            addCriterion("coding_id =", value, "codingId");
            return (Criteria) this;
        }

        public Criteria andCodingIdNotEqualTo(Integer value) {
            addCriterion("coding_id <>", value, "codingId");
            return (Criteria) this;
        }

        public Criteria andCodingIdGreaterThan(Integer value) {
            addCriterion("coding_id >", value, "codingId");
            return (Criteria) this;
        }

        public Criteria andCodingIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("coding_id >=", value, "codingId");
            return (Criteria) this;
        }

        public Criteria andCodingIdLessThan(Integer value) {
            addCriterion("coding_id <", value, "codingId");
            return (Criteria) this;
        }

        public Criteria andCodingIdLessThanOrEqualTo(Integer value) {
            addCriterion("coding_id <=", value, "codingId");
            return (Criteria) this;
        }

        public Criteria andCodingIdIn(List<Integer> values) {
            addCriterion("coding_id in", values, "codingId");
            return (Criteria) this;
        }

        public Criteria andCodingIdNotIn(List<Integer> values) {
            addCriterion("coding_id not in", values, "codingId");
            return (Criteria) this;
        }

        public Criteria andCodingIdBetween(Integer value1, Integer value2) {
            addCriterion("coding_id between", value1, value2, "codingId");
            return (Criteria) this;
        }

        public Criteria andCodingIdNotBetween(Integer value1, Integer value2) {
            addCriterion("coding_id not between", value1, value2, "codingId");
            return (Criteria) this;
        }

        public Criteria andGeoCodeIsNull() {
            addCriterion("geo_code is null");
            return (Criteria) this;
        }

        public Criteria andGeoCodeIsNotNull() {
            addCriterion("geo_code is not null");
            return (Criteria) this;
        }

        public Criteria andGeoCodeEqualTo(String value) {
            addCriterion("geo_code =", value, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeNotEqualTo(String value) {
            addCriterion("geo_code <>", value, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeGreaterThan(String value) {
            addCriterion("geo_code >", value, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeGreaterThanOrEqualTo(String value) {
            addCriterion("geo_code >=", value, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeLessThan(String value) {
            addCriterion("geo_code <", value, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeLessThanOrEqualTo(String value) {
            addCriterion("geo_code <=", value, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeLike(String value) {
            addCriterion("geo_code like", value, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeNotLike(String value) {
            addCriterion("geo_code not like", value, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeIn(List<String> values) {
            addCriterion("geo_code in", values, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeNotIn(List<String> values) {
            addCriterion("geo_code not in", values, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeBetween(String value1, String value2) {
            addCriterion("geo_code between", value1, value2, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeNotBetween(String value1, String value2) {
            addCriterion("geo_code not between", value1, value2, "geoCode");
            return (Criteria) this;
        }

        public Criteria andTimeCodeIsNull() {
            addCriterion("time_code is null");
            return (Criteria) this;
        }

        public Criteria andTimeCodeIsNotNull() {
            addCriterion("time_code is not null");
            return (Criteria) this;
        }

        public Criteria andTimeCodeEqualTo(String value) {
            addCriterion("time_code =", value, "timeCode");
            return (Criteria) this;
        }

        public Criteria andTimeCodeNotEqualTo(String value) {
            addCriterion("time_code <>", value, "timeCode");
            return (Criteria) this;
        }

        public Criteria andTimeCodeGreaterThan(String value) {
            addCriterion("time_code >", value, "timeCode");
            return (Criteria) this;
        }

        public Criteria andTimeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("time_code >=", value, "timeCode");
            return (Criteria) this;
        }

        public Criteria andTimeCodeLessThan(String value) {
            addCriterion("time_code <", value, "timeCode");
            return (Criteria) this;
        }

        public Criteria andTimeCodeLessThanOrEqualTo(String value) {
            addCriterion("time_code <=", value, "timeCode");
            return (Criteria) this;
        }

        public Criteria andTimeCodeLike(String value) {
            addCriterion("time_code like", value, "timeCode");
            return (Criteria) this;
        }

        public Criteria andTimeCodeNotLike(String value) {
            addCriterion("time_code not like", value, "timeCode");
            return (Criteria) this;
        }

        public Criteria andTimeCodeIn(List<String> values) {
            addCriterion("time_code in", values, "timeCode");
            return (Criteria) this;
        }

        public Criteria andTimeCodeNotIn(List<String> values) {
            addCriterion("time_code not in", values, "timeCode");
            return (Criteria) this;
        }

        public Criteria andTimeCodeBetween(String value1, String value2) {
            addCriterion("time_code between", value1, value2, "timeCode");
            return (Criteria) this;
        }

        public Criteria andTimeCodeNotBetween(String value1, String value2) {
            addCriterion("time_code not between", value1, value2, "timeCode");
            return (Criteria) this;
        }

        public Criteria andSourceCodeIsNull() {
            addCriterion("source_code is null");
            return (Criteria) this;
        }

        public Criteria andSourceCodeIsNotNull() {
            addCriterion("source_code is not null");
            return (Criteria) this;
        }

        public Criteria andSourceCodeEqualTo(String value) {
            addCriterion("source_code =", value, "sourceCode");
            return (Criteria) this;
        }

        public Criteria andSourceCodeNotEqualTo(String value) {
            addCriterion("source_code <>", value, "sourceCode");
            return (Criteria) this;
        }

        public Criteria andSourceCodeGreaterThan(String value) {
            addCriterion("source_code >", value, "sourceCode");
            return (Criteria) this;
        }

        public Criteria andSourceCodeGreaterThanOrEqualTo(String value) {
            addCriterion("source_code >=", value, "sourceCode");
            return (Criteria) this;
        }

        public Criteria andSourceCodeLessThan(String value) {
            addCriterion("source_code <", value, "sourceCode");
            return (Criteria) this;
        }

        public Criteria andSourceCodeLessThanOrEqualTo(String value) {
            addCriterion("source_code <=", value, "sourceCode");
            return (Criteria) this;
        }

        public Criteria andSourceCodeLike(String value) {
            addCriterion("source_code like", value, "sourceCode");
            return (Criteria) this;
        }

        public Criteria andSourceCodeNotLike(String value) {
            addCriterion("source_code not like", value, "sourceCode");
            return (Criteria) this;
        }

        public Criteria andSourceCodeIn(List<String> values) {
            addCriterion("source_code in", values, "sourceCode");
            return (Criteria) this;
        }

        public Criteria andSourceCodeNotIn(List<String> values) {
            addCriterion("source_code not in", values, "sourceCode");
            return (Criteria) this;
        }

        public Criteria andSourceCodeBetween(String value1, String value2) {
            addCriterion("source_code between", value1, value2, "sourceCode");
            return (Criteria) this;
        }

        public Criteria andSourceCodeNotBetween(String value1, String value2) {
            addCriterion("source_code not between", value1, value2, "sourceCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeIsNull() {
            addCriterion("carrier_code is null");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeIsNotNull() {
            addCriterion("carrier_code is not null");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeEqualTo(String value) {
            addCriterion("carrier_code =", value, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeNotEqualTo(String value) {
            addCriterion("carrier_code <>", value, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeGreaterThan(String value) {
            addCriterion("carrier_code >", value, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeGreaterThanOrEqualTo(String value) {
            addCriterion("carrier_code >=", value, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeLessThan(String value) {
            addCriterion("carrier_code <", value, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeLessThanOrEqualTo(String value) {
            addCriterion("carrier_code <=", value, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeLike(String value) {
            addCriterion("carrier_code like", value, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeNotLike(String value) {
            addCriterion("carrier_code not like", value, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeIn(List<String> values) {
            addCriterion("carrier_code in", values, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeNotIn(List<String> values) {
            addCriterion("carrier_code not in", values, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeBetween(String value1, String value2) {
            addCriterion("carrier_code between", value1, value2, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andCarrierCodeNotBetween(String value1, String value2) {
            addCriterion("carrier_code not between", value1, value2, "carrierCode");
            return (Criteria) this;
        }

        public Criteria andDisasterCodeIsNull() {
            addCriterion("disaster_code is null");
            return (Criteria) this;
        }

        public Criteria andDisasterCodeIsNotNull() {
            addCriterion("disaster_code is not null");
            return (Criteria) this;
        }

        public Criteria andDisasterCodeEqualTo(String value) {
            addCriterion("disaster_code =", value, "disasterCode");
            return (Criteria) this;
        }

        public Criteria andDisasterCodeNotEqualTo(String value) {
            addCriterion("disaster_code <>", value, "disasterCode");
            return (Criteria) this;
        }

        public Criteria andDisasterCodeGreaterThan(String value) {
            addCriterion("disaster_code >", value, "disasterCode");
            return (Criteria) this;
        }

        public Criteria andDisasterCodeGreaterThanOrEqualTo(String value) {
            addCriterion("disaster_code >=", value, "disasterCode");
            return (Criteria) this;
        }

        public Criteria andDisasterCodeLessThan(String value) {
            addCriterion("disaster_code <", value, "disasterCode");
            return (Criteria) this;
        }

        public Criteria andDisasterCodeLessThanOrEqualTo(String value) {
            addCriterion("disaster_code <=", value, "disasterCode");
            return (Criteria) this;
        }

        public Criteria andDisasterCodeLike(String value) {
            addCriterion("disaster_code like", value, "disasterCode");
            return (Criteria) this;
        }

        public Criteria andDisasterCodeNotLike(String value) {
            addCriterion("disaster_code not like", value, "disasterCode");
            return (Criteria) this;
        }

        public Criteria andDisasterCodeIn(List<String> values) {
            addCriterion("disaster_code in", values, "disasterCode");
            return (Criteria) this;
        }

        public Criteria andDisasterCodeNotIn(List<String> values) {
            addCriterion("disaster_code not in", values, "disasterCode");
            return (Criteria) this;
        }

        public Criteria andDisasterCodeBetween(String value1, String value2) {
            addCriterion("disaster_code between", value1, value2, "disasterCode");
            return (Criteria) this;
        }

        public Criteria andDisasterCodeNotBetween(String value1, String value2) {
            addCriterion("disaster_code not between", value1, value2, "disasterCode");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table unified_code
     *
     * @mbggenerated do_not_delete_during_merge Sat Nov 04 10:17:33 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table unified_code
     *
     * @mbggenerated Sat Nov 04 10:17:33 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}