package com.qiu.pojo;

public class videoTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VideoTable.video_id
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    private Integer videoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VideoTable.video_data
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    private byte[] videoData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VideoTable.video_id
     *
     * @return the value of VideoTable.video_id
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VideoTable.video_id
     *
     * @param videoId the value for VideoTable.video_id
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VideoTable.video_data
     *
     * @return the value of VideoTable.video_data
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    public byte[] getVideoData() {
        return videoData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VideoTable.video_data
     *
     * @param videoData the value for VideoTable.video_data
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    public void setVideoData(byte[] videoData) {
        this.videoData = videoData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VideoTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", videoId=").append(videoId);
        sb.append(", videoData=").append(videoData);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VideoTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        videoTable other = (videoTable) that;
        return (this.getVideoId() == null ? other.getVideoId() == null : this.getVideoId().equals(other.getVideoId()))
            && (this.getVideoData() == null ? other.getVideoData() == null : this.getVideoData().equals(other.getVideoData()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VideoTable
     *
     * @mbggenerated Sat Nov 25 20:04:19 CST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getVideoId() == null) ? 0 : getVideoId().hashCode());
        result = prime * result + ((getVideoData() == null) ? 0 : getVideoData().hashCode());
        return result;
    }
}